### ISSUE TITLE
Uncaught TypeError: Cannot read property 'UICorePlugin' of undefined

### ISSUE THREAD

**Issue by chakree30584** [bikegriffith/clappr-playback-rate-plugin#1]
I got those error in console after using this plugin

Uncaught TypeError: Cannot read property 'UICorePlugin' of undefined
Uncaught ReferenceError: PlaybackRatePlugin is not defined

**Comment by bikegriffith** [comment]
How are you importing and instantiating the plugin?  ES6? In-browser?

**Comment by chakree30584** [comment]
In-browser, 
after taking a look
I fixed by change all lower-case c clappr to Clappr in clappr-playback-rate-plugin.js

and everything is working great now, Thanks

**Comment by bikegriffith** [comment]
This should be fixed now.  Released 0.1.1 to npm.

**Comment by katsar0v** [comment]
Still having this issue with `master` and latest release at the moment

**Comment by katsar0v** [comment]
Still having this issue:
![image](https://user-images.githubusercontent.com/7236157/75700325-2e5cf700-5cb2-11ea-88ce-e526aa2269d3.png)
(file is renamed to clappr-speed.min.js)
